# Generated by Django 3.2.15 on 2022-09-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='movie_name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
