# Generated by Django 3.2.15 on 2022-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_imdb_movie_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imdb',
            index=models.Index(condition=models.Q(('movie_name__isnull', False)), fields=['movie_name'], name='movie_title_index'),
        ),
    ]
